services:
  redis:
    image: redis:7-alpine
    container_name: local-redis
    ports:
      - '6379:6379'
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - '5540:5540'
    restart: unless-stopped
