/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapsRouteImport } from './routes/swaps'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'

const SwapsRoute = SwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/components': typeof ComponentsRoute
  '/fairness': typeof FairnessRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRouteWithChildren
  '/swaps': typeof SwapsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/components': typeof ComponentsRoute
  '/fairness': typeof FairnessRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRouteWithChildren
  '/swaps': typeof SwapsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/compliance': typeof ComplianceRoute
  '/components': typeof ComponentsRoute
  '/fairness': typeof FairnessRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRouteWithChildren
  '/swaps': typeof SwapsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/compliance'
    | '/components'
    | '/fairness'
    | '/login'
    | '/notifications'
    | '/schedule'
    | '/settings'
    | '/swaps'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/compliance'
    | '/components'
    | '/fairness'
    | '/login'
    | '/notifications'
    | '/schedule'
    | '/settings'
    | '/swaps'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/compliance'
    | '/components'
    | '/fairness'
    | '/login'
    | '/notifications'
    | '/schedule'
    | '/settings'
    | '/swaps'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  ComplianceRoute: typeof ComplianceRoute
  ComponentsRoute: typeof ComponentsRoute
  FairnessRoute: typeof FairnessRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SwapsRoute: typeof SwapsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swaps': {
      id: '/swaps'
      path: '/swaps'
      fullPath: '/swaps'
      preLoaderRoute: typeof SwapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  ComplianceRoute: ComplianceRoute,
  ComponentsRoute: ComponentsRoute,
  FairnessRoute: FairnessRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SwapsRoute: SwapsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
